#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure custom HTTP response header
sudo sed -i '/server_name _;/a \\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
