#!/bin/bash

# Update the system and install HAproxy
sudo apt update
sudo apt install haproxy -y

# Configure HAproxy to send traffic to web-01 and web-02 using roundrobin algorithm
sudo tee /etc/haproxy/haproxy.cfg <<EOF
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 STUDENT_ID-web-01:80 check
    server web-02 STUDENT_ID-web-02:80 check
EOF

# Make sure HAproxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAproxy service to apply the changes
sudo systemctl restart haproxy

